#!/bin/bash
#
# launch
#
# Simple wrapper that launches either the manager or the runner
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if (( $# != 3 ))
then
  echo "usage: $0 service-name [service-instance|manager] service-address"
  exit 1
fi

name="$1"
instance="$2"
address="$3"

if [ -z "$COUCHDB_URL" ]
then
  export COUCHDB_URL="http://127.0.0.1:5984/services"
fi

if [ "$instance" = "manager" ]
then
  exec "$DIR"/manager "$name" "$address"
else
  exec "$DIR"/runner "$name" "$instance" "$address"
fi

