#!/bin/bash
set -u
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if (( $# != 3 ))
then
  echo "usage: $0 service-name [service-instance|manager] service-address"
  exit 1
fi

name="$1"
instance="$2"
address="$3"

if [ "$instance" = "manager" ]
then
  exec "$DIR"/manager "$name" "$address"
else
  exec "$DIR"/run "$name" "$instance" "$address"
fi

